New log file opened at Sun May 24 14:29:24 JST 2015 by 8940@kengo-PCn
Taking next connection to: 49314
New client attempting to connect on port: 49315-49314
  Address = /192.168.169.1:49314
This client on port 49315 has uuid 0ac1125c-116f-414c-af80-27c0d350a90f configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-0ac1125c-116f-414c-af80-27c0d350a90f
Taking next connection to: 49314
New client attempting to connect on port: 49316-49314
  Address = /192.168.169.1:49314
Handshake exception on socket: 49316
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49314
New client attempting to connect on port: 49317-49314
  Address = /192.168.169.1:49314
This client on port 49317 has uuid a070b6d2-03c4-4930-8d01-5be4c211a435 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-0ac1125c-116f-414c-af80-27c0d350a90f, activator-a070b6d2-03c4-4930-8d01-5be4c211a435
Taking next connection to: 49314
New client attempting to connect on port: 49318-49314
  Address = /192.168.169.1:49314
Handshake exception on socket: 49318
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49314
New client attempting to connect on port: 49319-49314
  Address = /192.168.169.1:49314
This client on port 49319 has uuid 5deb9187-d15e-44cf-b078-73810945f79f configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-0ac1125c-116f-414c-af80-27c0d350a90f, activator-a070b6d2-03c4-4930-8d01-5be4c211a435, play-fork-run-5deb9187-d15e-44cf-b078-73810945f79f
Taking next connection to: 49314
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49314
